export class TaskFlatNode {
  constructor(
    public company: string,
    public project_code: string,
    public parent_id: number,
    public id: number,
    public level:number,
    public title: string,
    public emp_id: string,
    public phase: string,
    public plan_start_date: string,
    public plan_end_date: string,
    public actual_start_date: string,
    public actual_end_date: string,
    public progressDates: string[],
    public point: number,
    public wk_est: number,
    public wk_plan: number,
    public wk_act: number,
    public progress_plan: number,
    public progress_act: number,
    public change_count: number,
    public create_emp_id: string,
    public create_datetime: string,
    public change_emp_id: string,
    public change_datetime: string,
    public data_flag: string,
    public expanded: boolean,
    public expandable: boolean, 
  ) {}
}
